set nocompatible               " be iMproved
filetype off                   " required!

" Before bundles
source ~/dotfiles/.vim/before.vim

" Vundle
" set rtp+=~/dotfiles/.vim/bundle/vundle/
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

" Source bundle config
source ~/dotfiles/.vim/bundles.vim

call vundle#end()            " required
filetype plugin indent on    " required

" After
source ~/dotfiles/.vim/after.vim

" Host specific configs
if filereadable(glob("~/.vimrc.local")) 
    source ~/.vimrc.local
endif
