#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

export LIBVA_DRIVER_NAME=vdpau
export ZDOTDIR=$HOME/dotfiles
export GOPATH=$HOME/go
export PATH=$PATH:$GOPATH/bin:$HOME/bin

# Source Prezto.
if [[ -s "$HOME/dotfiles/.zprezto/init.zsh" ]]; then
  source "$HOME/dotfiles/.zprezto/init.zsh"
fi

# Customize to your needs...
if [ -d "$HOME/.linuxbrew/bin" ] ; then
    export PATH="$HOME/.linuxbrew/bin:$PATH"
    export MANPATH="$HOME/.linuxbrew/share/man:$MANPATH"
    export INFOPATH="$HOME/.linuxbrew/share/info:$INFOPATH"
fi

if [[ -s "$HOME/.dircolors" ]]; then
    eval `dircolors $HOME/.dircolors`
fi


[[ -s $HOME/.nvm/nvm.sh ]] && . $HOME/.nvm/nvm.sh # This loads NVM

PATH=$PATH:$HOME/.rvm/bin # Add RVM to PATH for scripting
