#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#
export ZDOTDIR=$HOME/dotfiles
export GOPATH=$HOME/go
export PATH=$PATH:$GOPATH/bin

# Source Prezto.
if [[ -s "$HOME/dotfiles/.zprezto/init.zsh" ]]; then
  source "$HOME/dotfiles/.zprezto/init.zsh"
fi

# Customize to your needs...

