#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

export XDG_CONFIG_HOME=$HOME/.config
export XDG_CACHE_HOME=$HOME/.cache
export XDG_DATA_HOME=$HOME/.local/share

export HTTPIE_CONFIG_DIR="$XDG_CONFIG_HOME/httpie"

export LIBVA_DRIVER_NAME=vdpau
export ZDOTDIR=$HOME/dotfiles
export GOPATH=$HOME/go
export PATH=$GOPATH/bin:$HOME/bin:$PATH

export FZF_DEFAULT_COMMAND='ag -g ""' 

# Source Prezto.
if [[ -s "$HOME/dotfiles/.zprezto/init.zsh" ]]; then
  source "$HOME/dotfiles/.zprezto/init.zsh"
fi

# Customize to your needs...
if [ -d "$HOME/.linuxbrew/bin" ] ; then
    export PATH="$HOME/.linuxbrew/bin:$PATH"
    export MANPATH="$HOME/.linuxbrew/share/man:$MANPATH"
    export INFOPATH="$HOME/.linuxbrew/share/info:$INFOPATH"
fi

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

alias vim="nvim"
